## @file
# Mergify YML file that automatically merges a GitHub pull request against
# master if all of the GitHub branch protections have passed.
#
# Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# https://github.com/apps/mergify
# https://doc.mergify.io/
#
##

pull_request_rules:
  - name: automatic merge when GitHub branch protection passes
    conditions:
      - base=master
    actions:
      merge:
        strict: true
        method: rebase
  - name: auotmatically close a PR that can not be merged due to a merge conflict
    conditions:
      - base=master
      - conflict
    actions:
      close:
        message: PR can not be merged due to conflict.  Please rebase and resubmit
  - name: automatically close a PR that fails the EDK II Maintainers membership check
    conditions:
      - base=master
      - status-failure=mdkinney.ATest
    actions:
      close:
        message: PR submitter is not a member of the Tianocore EDK II Maintainers team
