pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=mdkinney.ATest
    actions:
      merge:
        strict: true
        method: rebase