## @file
# Mergify YML file that automatically merges a GitHub pull request against
# edk2-ci if all of the GitHub branch protections have passed.  It also
# contains rules to:
# * auto close branches that are not from an EDK II Maintainer
# * post a comment on pull requests that have merge conflicts.
# * post a comment on pull requests that have PatchCheck.py errors.
#
# Configuration Notes:
# * Update the 'base=edk2-ci' statements with the name of the branch to merge
#   pull requests.
#
# * Update the 'status-failure' statement with the name of the name of the Azure
#   Pipelines Build that performs the EDK II Maintainer check.
#
# * This file must be checked into the 'default' branch of a repo.  Copies
#   of this file on other branches of a repo are ignored by Mergify.
#
# Copyright (c) 2019, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# https://github.com/apps/mergify
# https://doc.mergify.io/
#
##

pull_request_rules:

  - name: Automatically merge a PR when all required checks pass and 'push' label is present
    conditions:
      - base=master
      - label=push
      - author=mdkinney
      - status-success=mdkinney.PatchCheck
      - status-success=mdkinney.PatchCheck (CPU)
      - status-success=mdkinney.PatchCheck (MDE)
    actions:
      merge:
        strict: true
        method: rebase

  - name: Automatically add label 'close' to a PR when all required checks pass and 'push' label is not present
    conditions:
      - base=master
      - -label=push
      - -closed
      - status-success=mdkinney.PatchCheck
      - status-success=mdkinney.PatchCheck (CPU)
      - status-success=mdkinney.PatchCheck (MDE)
      - status-success=mdkinney.PatchCheck (SUCCESS)
      - status-success=mdkinney.PatchCheck (CPU) (SUCCESS)
      - status-success=mdkinney.PatchCheck (MDE) (SUCCESS)
    actions:
      close:
        message: All checks passed. Auto close personal build.

  - name: Post a comment on a PR that can not be merged due to a merge conflict
    conditions:
      - base=master
      - conflict
    actions:
      comment:
        message: PR can not be merged due to conflict.  Please rebase and resubmit

  - name: Automatically close a PR that fails the EDK II Maintainers membership check and 'push' label is present
    conditions:
      - base=master
      - label=push
      - -author=mdkinney
    actions:
      close:
        message: PR submitter is not a member of the Tianocore EDK II Maintainers team

  - name: Post a comment on a PR if any required check fails
    conditions:
      - base=master
      - status-failure=mdkinney.PatchCheck
      - status-success=mdkinney.PatchCheck (FAILED)
    actions:
      comment:
        message: PR can not be merged due to a check failure.  Please resolve and resubmit

  - name: Post a comment on a PR if any required check fails
    conditions:
      - base=master
      - status-failure=mdkinney.PatchCheck (CPU)
      - status-success=mdkinney.PatchCheck (CPU) (FAILED)
    actions:
      comment:
        message: PR can not be merged due to a check failure.  Please resolve and resubmit

  - name: Post a comment on a PR if any required check fails
    conditions:
      - base=master
      - status-failure=mdkinney.PatchCheck (MDE)
      - status-success=mdkinney.PatchCheck (MDE) (FAILED)
    actions:
      comment:
        message: PR can not be merged due to a check failure.  Please resolve and resubmit
