## @file
# Assign reviewers
#
# Copyright (c) 2022, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Assign reviewers from .github/REVIEWERS using CODEWONERS syntax

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master
      - 'releases/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump Requested Reviewers
        env:
          REVIEWER_CONTEXT: ${{ toJSON(github.event.pull_request.requested_reviewers) }}
        run: echo "$REVIEWER_CONTEXT"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v3
      - run: git log --oneline ${{ github.event.pull_request.base.sha }}
      - run: git log --oneline ${{ github.event.pull_request.head.sha }}
      - run: git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v2
      - run: pip install codeowners GitPython PyGithub
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            from codeowners import CodeOwners
            from git import Git
            from github import Github
            reviewers = CodeOwners(open('.github/REVIEWERS').read())
            repo = Git('.')
            print ('Files in repo')
            for File in repo.ls_files().split():
                print ('  ', File, reviewers.of(File))
            print ('Files in PR')
            for File in repo.diff('${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}}','--name-only').split():
                print ('  ', File, reviewers.of(File))
            Hub = Github('${{ secrets.GITHUB_TOKEN }}')
            print ('Hub:', Hub)
